### ISSUE TITLE
Dashboard Broke

### ISSUE THREAD

**Issue by justinreed23** [donbowen/portfolio-frontier-streamlit-dashboard#1]
Hi, it seems like the dashboard is broken on streamlit. 

![image](https://github.com/donbowen/portfolio-frontier-streamlit-dashboard/assets/123396887/a726b525-17c4-43af-826f-eef5b8be4021)
 
(I cloned your repo and it also doesn't work for me and I can't figure it out for the life of me)

**Comment by donbowen** [comment]
Huh. I’ll look into it. My guess is a traffic overload or general issues with streamlit but that’s a wild guess.

**Comment by donbowen** [comment]
Appears to be a broader streamlit issue: https://ssls-airbnb-analysis.streamlit.app/

this repo is also down, but it’s not my account 

I’m guessing it will be fixed soon

**Comment by justinreed23** [comment]
Thank god, I was so confused

**Comment by donbowen** [comment]
https://github.com/LeDataSciFi/ledatascifi-2024/discussions/33
